package geopositions.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Positions")
public class GeoPosition {
	
	private String id;
	private double longitude;
	private double lattitude;
	private String date;
	private String infos;
	
	
	public GeoPosition() {
		super();
	}
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="longitude")
	public double getLongitude() {
		return longitude;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	@DynamoDBAttribute(attributeName="lattitude")
	public double getLattitude() {
		return lattitude;
	}
	public void setLattitude(double lattitude) {
		this.lattitude = lattitude;
	}
	
	@DynamoDBAttribute(attributeName="date")
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	
	@DynamoDBAttribute(attributeName="infos")
	public String getInfos() {
		return infos;
	}
	public void setInfos(String infos) {
		this.infos = infos;
	}

	@Override
	public String toString() {
		return "GeoPosition [id=" + id + ", longitude=" + longitude + ", lattitude=" + lattitude + ", date=" + date
				+ ", infos=" + infos + "]";
	}
	
	
	

}
